// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT9ZlMCvNtWWBvNAmJEBKbfVj9Uoj1KCE',
    appId: '1:203693981909:web:bb9c78dd0558bd3a20e25c',
    messagingSenderId: '203693981909',
    projectId: 'new-ecommerce-f86eb',
    authDomain: 'new-ecommerce-f86eb.firebaseapp.com',
    storageBucket: 'new-ecommerce-f86eb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPXveOX5LC5XZs4xnnyVYSpoFQTvprsCI',
    appId: '1:203693981909:android:c43bb420a081621620e25c',
    messagingSenderId: '203693981909',
    projectId: 'new-ecommerce-f86eb',
    storageBucket: 'new-ecommerce-f86eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq49wcb4qiMxDRO8jDlloqrPeN3T1QmIw',
    appId: '1:203693981909:ios:7ced2f33582d342e20e25c',
    messagingSenderId: '203693981909',
    projectId: 'new-ecommerce-f86eb',
    storageBucket: 'new-ecommerce-f86eb.appspot.com',
    iosClientId: '203693981909-10v9bfjeqvg796hqs83b9fhvjp6ur9oi.apps.googleusercontent.com',
    iosBundleId: 'com.example.newEcomerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBq49wcb4qiMxDRO8jDlloqrPeN3T1QmIw',
    appId: '1:203693981909:ios:e1079aecf0b4f20620e25c',
    messagingSenderId: '203693981909',
    projectId: 'new-ecommerce-f86eb',
    storageBucket: 'new-ecommerce-f86eb.appspot.com',
    iosClientId: '203693981909-2fkethkb9f2rhib6f47qlufj46s7aufh.apps.googleusercontent.com',
    iosBundleId: 'com.example.newEcomerce.RunnerTests',
  );
}
